Description: >
  Bankole/Project2
  servers autoscaling, loadbalancing and some other groups needed for this project

Parameters:
    
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:

  ProfileWithRolesForOurApp:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - S3ReadOnlyEc2

  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Alllow http to our hosts
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
    
  LBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our load balancer
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
  WebAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          echo "it works! Udagram, Udacity" > index.html    
         
      ImageId: ami-005de95e8ff495156
      SecurityGroups:
      - Ref: WebServerSecGroup
      InstanceType: t2.xlarge
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdk"
        Ebs:
          VolumeSize: '10'

  WebAppGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - Fn::ImportValue:
          !Sub "${EnvironmentName}-PRIV-NETS"
      LaunchConfigurationName: 
        Ref: WebAppLaunchConfig
      MinSize: '2'
      MaxSize: '5'
      TargetGroupARNs:
        - Ref: WebAppTargetGroup

  WebAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
      - Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
      - Fn::ImportValue: !Sub "${EnvironmentName}-PUB2-SN"
      SecurityGroups:
       - Ref: LBSecGroup
      
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: WebAppTargetGroup
      LoadBalancerArn:
        Ref: WebAppLB
      Port: '80'
      Protocol: HTTP
  
  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref WebAppTargetGroup
      Conditions:
      - Field: path-pattern
        Values: [/]
      ListenerArn: !Ref 'Listener'
      Priority: 1
  
  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: 
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"

Outputs:
  WebAppDNS:
    Description: The link to our website
    Value:
      Fn::Join:
        - ''
        - - "http://"
          - Fn::GetAtt: WebAppLB.DNSName

  WebServerSecGroup:
    Description: A reference to the created Web Server Security Group
    Value: !Ref WebServerSecGroup
    Export:
      Name: !Sub ${EnvironmentName}-WEBSG
  
  Listener:
    Description: A reference to the created listerner for the load balancer
    Value: !Ref Listener
    Export:
      Name: !Sub ${EnvironmentName}-LTNER

  LBSecGroup:
    Description: A reference to the created Load balancer security group
    Value: !Ref LBSecGroup
    Export:
      Name: !Sub ${EnvironmentName}-LBSG
  
  WebAppGroup:
    Description: A reference to the created web application Group
    Value: !Ref WebAppGroup
    Export:
      Name: !Sub ${EnvironmentName}-WebAG

  ALBListenerRule:
    Description: A reference to the created Application Load balancer listener Rule
    Value: !Ref ALBListenerRule
    Export:
      Name: !Sub ${EnvironmentName}-ALBLR
    
  WebAppTargetGroup:
    Description: A reference to the created web application target Group
    Value: !Ref WebAppTargetGroup
    Export:
      Name: !Sub ${EnvironmentName}-WebATG
  
  
      
  
  
  
  


  
